name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 160.34.209.175 >> ~/.ssh/known_hosts

    - name: Deploy to Oracle VM with zero downtime
      run: |
        ssh ubuntu@160.34.209.175 << 'EOF'
          set -e
          cd pisa-job-application
          git pull origin main

          echo "Building new Docker image..."
          sudo docker build -t pisa-job-app .

          echo "Running new container on port 3001..."
          sudo docker run -d \
            --name pisa-app-temp \
            --env-file .env \
            -p 3001:3000 \
            pisa-job-app

          echo "Waiting a few seconds for app to initialize..."
          sleep 5

          echo "Health check (basic):"
          curl -f http://localhost:3001 || {
            echo "Health check failed. Aborting deployment."
            sudo docker rm -f pisa-app-temp
            exit 1
          }

          echo "Stopping and removing old container if it exists..."
          if [ \$(sudo docker ps -a -q -f name=pisa-app) ]; then
            sudo docker rm -f pisa-app
          fi

          echo "Starting new container on port 3000..."
          sudo docker run -d \
            --name pisa-app \
            --env-file .env \
            -p 3000:3000 \
            pisa-job-app

          echo "Removing temporary container..."
          sudo docker rm -f pisa-app-temp
        EOF
