name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 160.34.209.175 >> ~/.ssh/known_hosts

    - name: Deploy to Oracle VM and rebuild Docker container
      run: |
        ssh ubuntu@160.34.209.175 << 'EOF'
          cd pisa-job-application

          git pull origin main

          # Detener y eliminar cualquier contenedor usando el puerto 3000
          PORT=3000
          CONTAINERS=$(sudo docker ps -q --filter "publish=${PORT}")
          if [ -n "$CONTAINERS" ]; then
            echo "Stopping containers on port $PORT..."
            echo "$CONTAINERS" | xargs -r sudo docker stop
            sleep 2
            echo "$CONTAINERS" | xargs -r sudo docker rm -f
          fi

          # Matar cualquier proceso que esté usando el puerto 3000
          PID=$(sudo lsof -t -i:${PORT})
          if [ -n "$PID" ]; then
            echo "Killing process using port $PORT: PID $PID"
            sudo kill -9 $PID
            sleep 2
          fi

          # Construir imagen
          sudo docker build -t pisa-job-app .

          # Correr contenedor
          sudo docker run -d \
            --name pisa-app \
            --env-file .env \
            -p 3000:3000 \
            pisa-job-app
        EOF

