name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 160.34.209.175 >> ~/.ssh/known_hosts

    - name: Deploy to Oracle VM and rebuild Docker container
      run: |
        ssh ubuntu@160.34.209.175 << 'EOF'
          cd pisa-job-application

          git pull origin main

          # Detener cualquier contenedor que use el puerto 3000
          sudo docker ps -q --filter "publish=3000" | xargs -r docker stop

          # Eliminar el contenedor anterior si existe
          sudo docker rm -f pisa-app || true

          # Construir la imagen con un tag específico
          sudo docker build -t pisa-job-app .

          # Ejecutar el contenedor con un nombre específico y --rm
          sudo docker run --rm \
            --name pisa-app \
            --env-file .env \
            -p 3000:3000 \
            pisa-job-app
        EOF
